development:
  adapter: mysql2
  encoding: utf8
  database: tweets_development
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  encoding: utf8
  database: tweets_test
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: pg
  encoding: utf8
  database: tweets_production
  username: root
  password:

cucumber:
  <<: *test